#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

. .builder

npm install

mkdir -p target/

mkdir -p target/pub/

if [ -d source/pub.favicon/ ]; then

  for entry in source/pub.favicon/*; do

    copy_entry "$entry" "target/pub/${entry#source/pub.favicon/}"
  done
fi

for dir in source/*.*/; do
  
  dir="${dir%/}"
  
  name="${dir##*.}"
  
  dir2="${dir#source/}"
  dir2="${dir2%.*}"
  dir2="${dir2//.//}"

  build_js "$dir/$name.js" "target/$dir2/$name.js"
done

if [ -d source/pub.robots/ ]; then

  copy_entry source/pub.robots/robots.txt target/pub/robots.txt
fi

echo -e "\nDone"
